/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLayoutImport } from './routes/_auth/_layout'
import { Route as AuthLayoutSettingsImport } from './routes/_auth/_layout/settings'
import { Route as AuthLayoutOverviewImport } from './routes/_auth/_layout/overview'
import { Route as AuthLayoutInvoicesIndexImport } from './routes/_auth/_layout/invoices.index'
import { Route as AuthLayoutClientsIndexImport } from './routes/_auth/_layout/clients.index'
import { Route as AuthLayoutInvoicesCreateImport } from './routes/_auth/_layout/invoices.create'
import { Route as AuthLayoutInvoicesIdImport } from './routes/_auth/_layout/invoices.$id'
import { Route as AuthLayoutClientsCreateImport } from './routes/_auth/_layout/clients.create'
import { Route as AuthLayoutClientsIdImport } from './routes/_auth/_layout/clients.$id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLayoutSettingsRoute = AuthLayoutSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutOverviewRoute = AuthLayoutOverviewImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutInvoicesIndexRoute = AuthLayoutInvoicesIndexImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutClientsIndexRoute = AuthLayoutClientsIndexImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutInvoicesCreateRoute = AuthLayoutInvoicesCreateImport.update({
  id: '/invoices/create',
  path: '/invoices/create',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutInvoicesIdRoute = AuthLayoutInvoicesIdImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutClientsCreateRoute = AuthLayoutClientsCreateImport.update({
  id: '/clients/create',
  path: '/clients/create',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutClientsIdRoute = AuthLayoutClientsIdImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_layout/overview': {
      id: '/_auth/_layout/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthLayoutOverviewImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/settings': {
      id: '/_auth/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthLayoutSettingsImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/clients/$id': {
      id: '/_auth/_layout/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthLayoutClientsIdImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/clients/create': {
      id: '/_auth/_layout/clients/create'
      path: '/clients/create'
      fullPath: '/clients/create'
      preLoaderRoute: typeof AuthLayoutClientsCreateImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/invoices/$id': {
      id: '/_auth/_layout/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthLayoutInvoicesIdImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/invoices/create': {
      id: '/_auth/_layout/invoices/create'
      path: '/invoices/create'
      fullPath: '/invoices/create'
      preLoaderRoute: typeof AuthLayoutInvoicesCreateImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/clients/': {
      id: '/_auth/_layout/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthLayoutClientsIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/_layout/invoices/': {
      id: '/_auth/_layout/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthLayoutInvoicesIndexImport
      parentRoute: typeof AuthLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthLayoutOverviewRoute: typeof AuthLayoutOverviewRoute
  AuthLayoutSettingsRoute: typeof AuthLayoutSettingsRoute
  AuthLayoutClientsIdRoute: typeof AuthLayoutClientsIdRoute
  AuthLayoutClientsCreateRoute: typeof AuthLayoutClientsCreateRoute
  AuthLayoutInvoicesIdRoute: typeof AuthLayoutInvoicesIdRoute
  AuthLayoutInvoicesCreateRoute: typeof AuthLayoutInvoicesCreateRoute
  AuthLayoutClientsIndexRoute: typeof AuthLayoutClientsIndexRoute
  AuthLayoutInvoicesIndexRoute: typeof AuthLayoutInvoicesIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutOverviewRoute: AuthLayoutOverviewRoute,
  AuthLayoutSettingsRoute: AuthLayoutSettingsRoute,
  AuthLayoutClientsIdRoute: AuthLayoutClientsIdRoute,
  AuthLayoutClientsCreateRoute: AuthLayoutClientsCreateRoute,
  AuthLayoutInvoicesIdRoute: AuthLayoutInvoicesIdRoute,
  AuthLayoutInvoicesCreateRoute: AuthLayoutInvoicesCreateRoute,
  AuthLayoutClientsIndexRoute: AuthLayoutClientsIndexRoute,
  AuthLayoutInvoicesIndexRoute: AuthLayoutInvoicesIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/overview': typeof AuthLayoutOverviewRoute
  '/settings': typeof AuthLayoutSettingsRoute
  '/clients/$id': typeof AuthLayoutClientsIdRoute
  '/clients/create': typeof AuthLayoutClientsCreateRoute
  '/invoices/$id': typeof AuthLayoutInvoicesIdRoute
  '/invoices/create': typeof AuthLayoutInvoicesCreateRoute
  '/clients': typeof AuthLayoutClientsIndexRoute
  '/invoices': typeof AuthLayoutInvoicesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/overview': typeof AuthLayoutOverviewRoute
  '/settings': typeof AuthLayoutSettingsRoute
  '/clients/$id': typeof AuthLayoutClientsIdRoute
  '/clients/create': typeof AuthLayoutClientsCreateRoute
  '/invoices/$id': typeof AuthLayoutInvoicesIdRoute
  '/invoices/create': typeof AuthLayoutInvoicesCreateRoute
  '/clients': typeof AuthLayoutClientsIndexRoute
  '/invoices': typeof AuthLayoutInvoicesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/_auth/_layout/overview': typeof AuthLayoutOverviewRoute
  '/_auth/_layout/settings': typeof AuthLayoutSettingsRoute
  '/_auth/_layout/clients/$id': typeof AuthLayoutClientsIdRoute
  '/_auth/_layout/clients/create': typeof AuthLayoutClientsCreateRoute
  '/_auth/_layout/invoices/$id': typeof AuthLayoutInvoicesIdRoute
  '/_auth/_layout/invoices/create': typeof AuthLayoutInvoicesCreateRoute
  '/_auth/_layout/clients/': typeof AuthLayoutClientsIndexRoute
  '/_auth/_layout/invoices/': typeof AuthLayoutInvoicesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/overview'
    | '/settings'
    | '/clients/$id'
    | '/clients/create'
    | '/invoices/$id'
    | '/invoices/create'
    | '/clients'
    | '/invoices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/overview'
    | '/settings'
    | '/clients/$id'
    | '/clients/create'
    | '/invoices/$id'
    | '/invoices/create'
    | '/clients'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/_auth/_layout'
    | '/_auth/_layout/overview'
    | '/_auth/_layout/settings'
    | '/_auth/_layout/clients/$id'
    | '/_auth/_layout/clients/create'
    | '/_auth/_layout/invoices/$id'
    | '/_auth/_layout/invoices/create'
    | '/_auth/_layout/clients/'
    | '/_auth/_layout/invoices/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_layout"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_auth/_layout": {
      "filePath": "_auth/_layout.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_layout/overview",
        "/_auth/_layout/settings",
        "/_auth/_layout/clients/$id",
        "/_auth/_layout/clients/create",
        "/_auth/_layout/invoices/$id",
        "/_auth/_layout/invoices/create",
        "/_auth/_layout/clients/",
        "/_auth/_layout/invoices/"
      ]
    },
    "/_auth/_layout/overview": {
      "filePath": "_auth/_layout/overview.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/settings": {
      "filePath": "_auth/_layout/settings.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/clients/$id": {
      "filePath": "_auth/_layout/clients.$id.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/clients/create": {
      "filePath": "_auth/_layout/clients.create.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/invoices/$id": {
      "filePath": "_auth/_layout/invoices.$id.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/invoices/create": {
      "filePath": "_auth/_layout/invoices.create.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/clients/": {
      "filePath": "_auth/_layout/clients.index.tsx",
      "parent": "/_auth/_layout"
    },
    "/_auth/_layout/invoices/": {
      "filePath": "_auth/_layout/invoices.index.tsx",
      "parent": "/_auth/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
